source 'https://rubygems.org'

# Specify your gem's dependencies in borderlands2.gemspec
gemspec

gem 'pry', '>= 0.10.0'

group :dev do
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'guard-yard'
  gem 'rspec'
  gem 'rubocop'
end
